#!/usr/bin/env sh
set -e

version() {
  echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
}

if [ -z "$TRAVIS_ELIXIR_VERSION" ] || [ $(version $TRAVIS_ELIXIR_VERSION) -ge $(version "1.10.0") ]; then
  mix compile --warnings-as-errors
  mix format --dry-run --check-formatted
  mix credo --strict
  mkdir -p priv/plts && mix dialyzer --halt-exit-status
fi

MIX_ENV=test mix test
MIX_ENV=test_phoenix mix test
make clean && MIX_ENV=test_no_nif mix test
